from enum import Enum


class ERequestType(Enum):
    ORDER_REQUEST_MOBILE = 1
    ORDER_REQUEST_WEB = 2
    MESSAGE_TO_DELIVERY = 3
    INFORMATION_REQUEST_MOBILE = 4
    INFORMATION_REQUEST_WEB = 5
    DELIVERY_REQUEST = 6
    ORDER_MONITORING = 7


